In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
ds=pd.read_csv("Original_data_with_more_rows.csv")
ds

Unnamed: 0  Gender EthnicGroup          ParentEduc     LunchType  \
0               0  female     group B   bachelor's degree      standard   
1               1  female     group C        some college      standard   
2               2  female     group B     master's degree      standard   
3               3    male     group A  associate's degree  free/reduced   
4               4    male     group C        some college      standard   
...           ...     ...         ...                 ...           ...   
30636         995    male     group C    some high school      standard   
30637         996    male     group E  associate's degree  free/reduced   
30638         997    male     group C        some college      standard   
30639         998    male     group A    some high school  free/reduced   
30640         999  female     group D  associate's degree      standard   

        TestPrep  MathScore  ReadingScore  WritingScore  
0           none         72            72            74  
1      completed         69            90            88  
2           none         90            95            93  
3           none         47            57            44  
4           none         76            78            75  
...          ...        ...           ...           ...  
30636       none         56            47            51  
30637       none         74            75            72  
30638       none         36            29            27  
30639  completed         43            34            39  
30640       none         52            68            66  

[30641 rows x 9 columns]

In [4]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Unnamed: 0    30641 non-null  int64 
 1   Gender        30641 non-null  object
 2   EthnicGroup   30641 non-null  object
 3   ParentEduc    30641 non-null  object
 4   LunchType     30641 non-null  object
 5   TestPrep      30641 non-null  object
 6   MathScore     30641 non-null  int64 
 7   ReadingScore  30641 non-null  int64 
 8   WritingScore  30641 non-null  int64 
dtypes: int64(4), object(5)
memory usage: 2.1+ MB


In [5]:
# Drop the unnnecessary column
ds.drop(columns=["Unnamed: 0"],inplace=True)

In [6]:
# check for duplicates
ds.duplicated().sum()

0

In [7]:
# finding missing values
ds.isnull().sum()

Gender          0
EthnicGroup     0
ParentEduc      0
LunchType       0
TestPrep        0
MathScore       0
ReadingScore    0
WritingScore    0
dtype: int64

In [8]:
ds["Gender"].unique()

array(['female', 'male'], dtype=object)

In [9]:
ds["EthnicGroup"].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [10]:
ds["ParentEduc"].unique()


array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [11]:
ds["LunchType"].unique()


array(['standard', 'free/reduced'], dtype=object)

In [12]:
ds["LunchType"] = ds["LunchType"].map({'standard': 1, 'free/reduced': 0})

In [13]:
ds["TestPrep"].unique()


array(['none', 'completed'], dtype=object)

In [14]:
ds["LunchType"].unique()

array([1, 0], dtype=int64)

In [15]:
ds["MathScore"].unique()


array([ 72,  69,  90,  47,  76,  71,  88,  40,  64,  38,  58,  65,  78,
        50,  18,  46,  54,  66,  44,  74,  73,  67,  70,  62,  63,  56,
        97,  81,  75,  57,  55,  53,  59,  82,  77,  33,  52,   0,  79,
        39,  45,  60,  61,  41,  49,  30,  80,  42,  27,  43,  68,  85,
        98,  87,  51,  99,  84,  91,  83,  89,  22, 100,  96,  94,  48,
        35,  34,  86,  92,  37,  28,  24,  26,  95,  36,  29,  32,  93,
        19,  23,   8,  31,  25,  21,  17,  20,  16,  11,  12,  13,  15,
         9,  10,  14], dtype=int64)

In [16]:
ds["ReadingScore"].unique()


array([ 72,  90,  95,  57,  78,  83,  43,  64,  60,  54,  52,  81,  53,
        75,  89,  32,  42,  58,  69,  73,  71,  74,  70,  65,  87,  56,
        61,  84,  55,  44,  41,  85,  59,  17,  39,  80,  37,  63,  51,
        49,  26,  68,  45,  47,  86,  34,  79,  66,  67,  91, 100,  76,
        77,  82,  92,  93,  62,  88,  50,  28,  48,  46,  23,  38,  94,
        97,  99,  31,  96,  24,  29,  40,  98,  35,  21,  30,  36,  33,
        19,  15,  25,  12,  20,  22,  27,  13,  16,  10], dtype=int64)

In [17]:
ds["WritingScore"].unique()

array([ 74,  88,  93,  44,  75,  78,  92,  39,  67,  50,  52,  43,  73,
        70,  58,  86,  28,  46,  61,  63,  53,  80,  72,  55,  65,  38,
        82,  79,  83,  59,  57,  54,  68,  66,  62,  76,  48,  42,  87,
        49,  10,  34,  71,  37,  56,  41,  22,  81,  45,  36,  89,  47,
        90, 100,  64,  98,  51,  40,  84,  69,  33,  60,  85,  91,  77,
        27,  94,  95,  19,  35,  32,  96,  97,  99,  15,  30,  23,  29,
        17,  31,  25,  24,  16,  26,  20,   7,  14,  18,  21,  13,   5,
        12], dtype=int64)

In [18]:
print(ds[["MathScore", "ReadingScore", "WritingScore"]].describe())

          MathScore  ReadingScore  WritingScore
count  30641.000000  30641.000000  30641.000000
mean      66.749355     69.624980     68.468327
std       15.206049     14.671572     15.307814
min        0.000000     10.000000      5.000000
25%       56.000000     60.000000     58.000000
50%       67.000000     70.000000     69.000000
75%       78.000000     80.000000     79.000000
max      100.000000    100.000000    100.000000


In [19]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Gender        30641 non-null  object
 1   EthnicGroup   30641 non-null  object
 2   ParentEduc    30641 non-null  object
 3   LunchType     30641 non-null  int64 
 4   TestPrep      30641 non-null  object
 5   MathScore     30641 non-null  int64 
 6   ReadingScore  30641 non-null  int64 
 7   WritingScore  30641 non-null  int64 
dtypes: int64(4), object(4)
memory usage: 1.9+ MB


In [20]:
print(ds.to_string)

<bound method DataFrame.to_string of        Gender EthnicGroup          ParentEduc  LunchType   TestPrep  \
0      female     group B   bachelor's degree          1       none   
1      female     group C        some college          1  completed   
2      female     group B     master's degree          1       none   
3        male     group A  associate's degree          0       none   
4        male     group C        some college          1       none   
...       ...         ...                 ...        ...        ...   
30636    male     group C    some high school          1       none   
30637    male     group E  associate's degree          0       none   
30638    male     group C        some college          1       none   
30639    male     group A    some high school          0  completed   
30640  female     group D  associate's degree          1       none   

       MathScore  ReadingScore  WritingScore  
0             72            72            74  
1             69

In [21]:
ds.to_csv("new_cleanesd_data.csv")